/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bandit.545 (https://sketchfab.com/Bandit.545)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/skyline-gt-r-r32-stylized-616b84304f7f48fab561b1aecbf2e130
title: Skyline GT-R R32 (Stylized)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import sky from './skyline.gltf';

export function Skyline(props) {
  const { nodes, materials } = useGLTF(sky)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 1.80, 0, -0.80]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.49, 0]} rotation={[-0.03, 0, 0.05]} scale={2.6}>
            <group position={[0, -0.19, 0]} scale={0.39}>
              <mesh geometry={nodes.Object_5.geometry} material={materials.R32_Col} />
              <mesh geometry={nodes.Object_6.geometry} material={materials.R32_Pal} />
              <mesh geometry={nodes.Object_7.geometry} material={materials.R32_Trans} />
              <mesh geometry={nodes.Object_8.geometry} material={materials.R32_Outline} />
            </group>
          </group>
          <group position={[0.75, 0.33, 1.29]} rotation={[0, -0.61, 0]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.R32_Pal} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.R32_Outline} />
          </group>
          <group position={[0.75, 0.33, -1.32]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.R32_Pal} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.R32_Outline} />
          </group>
          <group position={[-0.75, 0.33, 1.29]} rotation={[0, -0.61, 0]}>
            <group scale={[-1, 1, 1]}>
              <mesh geometry={nodes.Object_19.geometry} material={materials.R32_Pal} />
              <mesh geometry={nodes.Object_20.geometry} material={materials.R32_Outline} />
            </group>
          </group>
          <group position={[-0.75, 0.33, -1.32]}>
            <group scale={[-1, 1, 1]}>
              <mesh geometry={nodes.Object_23.geometry} material={materials.R32_Pal} />
              <mesh geometry={nodes.Object_24.geometry} material={materials.R32_Outline} />
            </group>
          </group>
          <mesh geometry={nodes.Object_26.geometry} material={materials.noise} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['noise.001']} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.noise} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/skyline.gltf')
